### PR TITLE
If an individual task is selected in a group, it is not executed due to files not copied

### PR DESCRIPTION
**Pull request by PiJoCoder**
See #207

### CODE REVIEW

**Comment by asavioli** [comment]
tested using the same example from issue #207 

First created a new pssdiag, using the version I have here 16.22.10.07. After selecting only Errorlog_all at shutdown, I can't see the file get_errorlogs.ps1

image


After performing the same test using this branch, I can see the missing file

image

**Review by asavioli — APPROVED** [review]
Tested the scenario of only collecting the error logs, and it worked fine!

**Comment by keeyu2** [comment]
I tried click one item on XEvent, Profiler Trace, perform, and custom diagnostics and it works as expected.

**Review by keeyu2 — COMMENTED** [review]
I tried click one item on XEvent, Profiler Trace, perform, and custom diagnostics and it works as expected.

**Comment by PiJoCoder** [comment]
> I tried click one item on XEvent, Profiler Trace, perform, and custom diagnostics and it works as expected.

Thanks

**Pull request merged**
