### PR TITLE
Update AzureDevOps-Pipelines.yml for Azure Pipelines to add SBOM manifest

### PR DESCRIPTION
**Pull request by PiJoCoder**
1.	Run Pipeline
2.	Review published artifacts folder a/_manifest/spdx_2.2/*.json (specifically manifest.spdx.json)

### CODE REVIEW

**Comment by PiJoCoder** [comment]
To meet SBOM requirement

**Comment by JamesFerebee** [comment]
Pipeline execution looks good

**Review by JamesFerebee — APPROVED** [review]
Test successful.

**Comment by PiJoCoder** [comment]
> Test successful.

Thanks

**Pull request merged**
