### PR TITLE
Upgrade of PSSDiag for Linux collectors to support new collectors and many fixes 

### PR DESCRIPTION
**Pull request by rl-msft**
Fix List
=================

Behavior:
Assuming that customers will have 1 instance (either host or container) pssdiag by default will collect from every instance on machine 
but we can adjust that if needed to limit to specific instance 

new Collectors:
. Docker collectors
. SQL AD Collector
. OS AD Collector
..reading krb5.conf for all currently enabled logs and collect them 
. OS HA Collector
. PAL DMVs Collector
. PAL logs collector
. cGroup top consumer 
. SQL process collector for all its configuration, memory maps, collect only child instance for host and container.
Enhancement
. SQL log collector now reads the actually location of the logs before collecting them, with additional pal log collector 
. Improve discovery process for container instance for host with multiple containers.
. adding example for my custom collector
. defaults changed
. adjusting output files so from name you can tell if this belong to container or host instance
Connectivity:
. Support Kerberos 
. new option (NONE) allows user to choose during runtime.
. Add support for pssdiag to run from within container, to support k8s deployments 

Scenarios
. Added the following new scenarios

		sql_perf_detailed_kube.scn
		sql_perf_general_kube.scn
		sql_perf_light_kube.scn
		sql_perf_minimal_kube.scn
		sql_perf_minimal.scn

Fixing different bugs and added many improvements 
. Adjusting Static collectors with all new Collectors 
. correct zombie sqlcmds when running inside container
. make sure that we can invoke sqlcmd regardless of the versions mssql-tools and mssql-tools18 works 
. support new image names
 
Removed features
. Remove Dump collector, will use Static instead 

Tool logging 
. Include all collection activities in the PSSDIAG log.

Has been tested on (remove any that don't apply):
SQL Linux 2017
SQL Linux 2019
SQL Linux 2022
SQL Linux Containers running K8s

### CODE REVIEW

**Review by PiJoCoder — APPROVED** [review]
Discussed with author. Much testing has been done by his team. Approving

**Review by PiJoCoder — CHANGES_REQUESTED** [review]
@rl-msft, can you review the pipeline rule failure before we merge.

**Comment by rl-msft** [comment]
@PiJoCoder I have finished making the change

**Comment by PiJoCoder** [comment]
> @PiJoCoder I have finished making the change

Great! I tested with the Pipeline and it completed successfully. I had to make a change in the pipeline and remove some task that is no longer supported but nothing to do with this. After that it succeeded.

**Review by PiJoCoder — APPROVED** [review]

**Pull request merged**
