### PR TITLE
Sql server perf stats snapshot ansavio

### PR DESCRIPTION
**Pull request by asavioli**
Fixes # .

Changes proposed in this pull request:
 -  Fixing an issue when collecting statistics info using the dmv sys.dm_db_stats_properties from instances where there are secondary replica databases with readable secondary disabled or read intent only. Currently it is failing and not collecting data from any databases of the whole instance

 - also replaced sys.dm_db_index_usage_stats by sys.stats, because the first one is initialized whenever SQL is restarted. Because of that, if customer collects the pssdiag right after restarting the instance (or not too long after a restart), a lot of  important statistics information is not being collected

How to test this code:
 - 
 - 
 - 

Has been tested on (remove any that don't apply):
 - Case-sensitive SQL Server instance
 - SQL Server 2008
 - SQL Server 2008 R2
 - SQL Server 2012
 - SQL Server 2014
 - SQL Server 2016
 - SQL Server 2017
 - SQL Server 2019
 - Azure SQL Virtual Machine
 - Amazon RDS

### CODE REVIEW

**Comment by PiJoCoder** [comment]
@SeanGallardy could you please review this change and provide any feedback?

**Comment by SeanGallardy** [comment]
Do we need to get stats from a secondary readable replica? What are the use cases for this?

**Comment by PiJoCoder** [comment]
@seangallardy, I'll let Andre explain it but I guess the use case is - your SQL Server can be having a perf problem and you need to gather PSSDIAG, but it may also happen to be a secondary and then the issues happen. @asavioli please elaborate on the scenario.

**Comment by asavioli** [comment]
good morning @SeanGallardy  and @PiJoCoder. I hope you are fine!

The main goal with this change is to solve an issue we have when there are databases from secondary replicas not readable along with databases from primary replicas and/or databases not part of an AG on the same instance. Currently, on this situation, the statistics data collection completely fails and nothing is collected from any databases. I added some selects to skip those databases from secondary replicas not readable 

But answering the question: I think it is interesting to collect statistics from secondary replica databases in cases where customers are complaining about performance issues on reports they run on the readable secondaries. In those cases, we can collect the pssdiag on the secondary replica only and will have all the data we need, including the stats. In case they are not up to date, we can recommend customers to solve it, updating them at the primary replica. Does it make sense?

Thanks!

**Comment by SeanGallardy** [comment]
@PiJoCoder Approved.

**Review by PiJoCoder — CHANGES_REQUESTED** [review]
Copied and tested the scenario. Looks good.
You may consider syncing from the upstream (main) because we just refreshed it yesterday with a lot of changes. 
  **git pull upstream master**
  
You may have to compute a new file hash using the Get-FileAttributes cmdlet which is inside \Confirm-FileAttributes.ps1

**Review by PiJoCoder — APPROVED** [review]
Tested with new hash and it works great

**Comment by PiJoCoder** [comment]
@seangallardy and @asavioli  thank you both!

**Pull request merged**
